### ISSUE TITLE
Add versioning support for "datastreams"

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#1]

**Comment by ajs6f** [comment]
I'd like to start this out by just engaging the native JCR notion of versioning-- IOT, let's don't start by being tied to Fedora's legacy abstractions. With that in mind, I can just add to the node type system already in place and annotate fedora:resource as versionable (by mixing in the snappily-named type mix:versionable). Then we should be able immediately to start playing with the version API. See:

http://www.day.com/maven/javax.jcr/javadocs/jcr-2.0/javax/jcr/version/VersionManager.html

for that. What say ye?

**Comment by cbeer** [comment]
+1. I think under the hood, we can (and should) do whatever makes sense. If we can expose that information in a legacy way, even better (so we don't need to mess with any of the projects whose tests suites already work against fcrepo 3.x).
