### ISSUE TITLE
Support the Fedora APIs used by Islandora

### ISSUE THREAD

**Issue by jonathangreen** [fcrepo4-archive/ff-modeshape-prototype#10]
I figured a ticket here would be the best place for this info. I'm not actually sure which ones are implemented right now.

We currently use:
getDatastreamDissemination
getDatastreamHistory (we could hack up the code a bit to just call getDatastream)
modifyDatastream
purgeDatastream
getObjectProfile
listDatastreams
modifyObject
addDatastream
getNextPid
upload
ingest (we always serialize to foxml and then ingest, but again for a demo we could fake that)
purgeObject

**Comment by cbeer** [comment]
For some of those APIs, how accurate a response do you need?
e.g., for Hydra, we needed GET /describe, but only for the <repositoryVersion> element. Anything like that for you?

(thinking esp. getObjectProfile, listDatastreams, etc?)

**Comment by ajs6f** [comment]
Jonathan-- I'm assigning to you so you can get a (as Chris implies) a rough description of the minimum return for Islandora for those methods. That available, I'll break this issue down as necessary and I'm betting we can turn it out in a day or so.
