### ISSUE TITLE
Update to Modeshape 3.1

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#11]
I'm supposed to look at scaling out modeshape today. It looks like there's stuff in modeshape 3.1 we might want.

http://modeshape.wordpress.com/2013/01/17/modeshape-3-1-0-final-is-available/

**Comment by ajs6f** [comment]
Cool-- should just be Maven work, right?

**Comment by cbeer** [comment]
should, if all goes well. and now we have basic tests to validate that.

**Comment by cbeer** [comment]
Fixed by 2cb454d8ddfbcc8465a29febb6bf29d4b1dc9b31
