### ISSUE TITLE
Figure out how to do modeshape clustering.

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#12]

**Comment by ajs6f** [comment]
Modeshape clustering is dumb and simple:

1) Start lots of Modeshape instances all aimed at the same Infinispan grid.

2) Cluster that grid.

So the secret name of this issue is "Figure out how to do Infinispan clustering."

**Comment by cbeer** [comment]
I figured out Infinispan clustering already:

https://docs.jboss.org/author/display/ISPN/Clustered+Configuration+QuickStart

It looks like there -is- something around modeshape clustering too (using JGroups), but all the docs I can find are for modeshape 2. There's an announcement: https://community.jboss.org/thread/174275

**Comment by ajs6f** [comment]
We can definitely move ahead with IS clustering. Hm. I'm trying to figure out what (if you've already configured clustering for persistence) what you might cluster from MS instance to MS instance. Maybe transient information? Or configuration?

**Comment by cbeer** [comment]
I gave IS clustering a try, but am clearly missing some key piece of knowledge.  I tried following the examples from:
https://github.com/infinispan/infinispan-quickstart/tree/master/clustered-cache

but kept running into some annoying low-level errors, e.g.:

```
WARN: Problems unmarshalling remote command from byte buffer
java.lang.ClassNotFoundException: org.infinispan.schematic.internal.SchematicEntryDelta
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
```

I'm going to take a break and then play with their clustered example a bit before trying to convert it to work for us.
