### ISSUE TITLE
Do a better job with the PID minter (can we tap into the UUIDs in JCR?)

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#3]

**Comment by ajs6f** [comment]
Yes!

How about a new "IdMinter" interface and immediate-default "JCRIdMinter" class (thinking about later possibilities for DI with Spring or Blueprint or whatever-you-like)?

**Comment by ajs6f** [comment]
Chris-- I'm not having a lot of fun getting the XACML sequencer to work (I think I'm misunderstanding something about the path expressions that map a portion of repository to a sequencer) so I'm going to pick up this issue in a 'PidMinter' branch.

**Comment by ajs6f** [comment]
See pull request.
