### ISSUE TITLE
Do we want to try to fake Fedora DC/RELS-EXT initial data?

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#4]

**Comment by ajs6f** [comment]
Wouldn't be too hard. Just some code to fill in some properties or template some RDF/XML content into an autogenerated child (actually, I think you could have the repo autogenerate the child based on the type system alone). (I would much rather fill in properties-- what's the point of using a graph store if you don't use it?)

Here's my question: how useful would this be to Hydra/Islandora.eSciDoc? Do people depend on those initial triples?

**Comment by ajs6f** [comment]
Do we have a canonical reference for what these data are? I'm looking at:

https://wiki.duraspace.org/display/FEDORA36/Triples+in+the+Resource+Index

but I'm not sure it's exactly on-point for us. Much of it involves the CMA.
