### ISSUE TITLE
Finish adding Fedora API parameters

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#6]
e.g. POST /ff/objects/asdf/datastreams/fdsa?mimeType=ZZZ, dsLabel, some notion of controlGroup?

**Comment by ajs6f** [comment]
0) MIMEtype we have in play, just got to get it mapped to the query param. I'll get it.

1) What's our JCR idea of dsLabel? How about a dc:title JCR property?

2) Ditto controlGroup. But JCR just doesn't seem to have anything that would match "INACTIVE" or "DELETED". There's just-- it's there, or it's not. I'm going to question this one-- I think we owe it to ourselves to talk a bit about how people do and don't use these states. Does the Hydra code use them at all?
