### ISSUE TITLE
Datastream history response

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#8]
Some hydra heads apparently use the datastream history:
GET /objects/sufia:hm50tr769/datastreams/content/history

Can we at least stub that out and return an empty history (or, history of 1 record only)? Or maybe versioning will be easy enough that we can move forward anyway.

**Comment by ajs6f** [comment]
Versioning is subtle. Versioning is _always_ subtle. So I'll stub it out quick, and we can think about versioning.

**Comment by ajs6f** [comment]
There is now a stub in place. Let me know if it needs to be more filled out.

**Comment by ajs6f** [comment]
I'll leave this open at least until Jonathan confirms/denies that Islandora is cool with the stub. I'm assuming that Hydra is okay with the empty XML that is now returned by the stub.
